In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('data_cleaned.csv')

In [4]:
data.head()

,country,year,cereal_yield,fdi_perc_gdp,en_per_gdp,en_per_cap,co2_ttl,co2_per_cap,co2_per_gdp,pop_urb_aggl_perc,prot_area_perc,gdp,gni_per_cap,under_5_mort_rate,pop_growth_perc,pop,urb_pop_growth_perc,urb_pop
0,AGO,1991,417.4,5.449515,179.271884,565.451027,4367.397,0.409949,129.971142,15.290728,12.399822,1.219375e+10,820.0,239.1,3.034866,10653515.0,6.687032,4.099473e+06
1,ARE,1991,1594.0,0.076475,245.977706,12262.388130,57010.849,29.851550,598.807980,26.377204,0.266886,3.391964e+10,19340.0,20.5,5.442852,1909812.0,5.265704,1.507988e+06
2,ARG,1991,2666.1,1.285579,173.122857,1434.960601,117021.304,3.536073,426.614517,39.119646,4.772468,1.897200e+11,3960.0,25.8,1.372593,33093579.0,1.762636,2.890393e+07
3,AUS,1991,1603.3,1.306912,208.686644,4926.727783,281530.258,16.288490,689.948873,60.356798,7.915273,3.299655e+11,18380.0,8.6,1.274577,17284000.0,1.438378,1.478473e+07
4,AUT,1991,5463.0,0.209142,128.939160,3381.073790,65888.656,8.448456,322.186648,19.746121,20.991143,1.721664e+11,21200.0,8.9,1.134999,7798899.0,1.134999,5.131676e+06

In [25]:
data['country'].nunique()

96

In [5]:
data1=data.copy()

In [6]:
data1.head()

,country,year,cereal_yield,fdi_perc_gdp,en_per_gdp,en_per_cap,co2_ttl,co2_per_cap,co2_per_gdp,pop_urb_aggl_perc,prot_area_perc,gdp,gni_per_cap,under_5_mort_rate,pop_growth_perc,pop,urb_pop_growth_perc,urb_pop
0,AGO,1991,417.4,5.449515,179.271884,565.451027,4367.397,0.409949,129.971142,15.290728,12.399822,1.219375e+10,820.0,239.1,3.034866,10653515.0,6.687032,4.099473e+06
1,ARE,1991,1594.0,0.076475,245.977706,12262.388130,57010.849,29.851550,598.807980,26.377204,0.266886,3.391964e+10,19340.0,20.5,5.442852,1909812.0,5.265704,1.507988e+06
2,ARG,1991,2666.1,1.285579,173.122857,1434.960601,117021.304,3.536073,426.614517,39.119646,4.772468,1.897200e+11,3960.0,25.8,1.372593,33093579.0,1.762636,2.890393e+07
3,AUS,1991,1603.3,1.306912,208.686644,4926.727783,281530.258,16.288490,689.948873,60.356798,7.915273,3.299655e+11,18380.0,8.6,1.274577,17284000.0,1.438378,1.478473e+07
4,AUT,1991,5463.0,0.209142,128.939160,3381.073790,65888.656,8.448456,322.186648,19.746121,20.991143,1.721664e+11,21200.0,8.9,1.134999,7798899.0,1.134999,5.131676e+06

In [11]:
data1['gdp'].dtype

dtype('float64')

In [12]:
data1['gdp'] = data1['gdp'].astype(float).apply(lambda x: '{:.0f}'.format(x))

In [18]:
data1['urb_pop'] = data1['urb_pop'].astype(float).apply(lambda x: '{:.0f}'.format(x))

In [13]:
data1['gdp']

0        12193746625
1        33919640390
2       189719989668
3       329965465819
4       172166366529
            ...
1695     90273764946
1696     26917363956
1697    275278721836
1698     11668379642
1699     14640794798
Name: gdp, Length: 1700, dtype: object

In [14]:
data1.columns.tolist()

['country',
 'year',
 'cereal_yield',
 'fdi_perc_gdp',
 'en_per_gdp',
 'en_per_cap',
 'co2_ttl',
 'co2_per_cap',
 'co2_per_gdp',
 'pop_urb_aggl_perc',
 'prot_area_perc',
 'gdp',
 'gni_per_cap',
 'under_5_mort_rate',
 'pop_growth_perc',
 'pop',
 'urb_pop_growth_perc',
 'urb_pop']

In [19]:
data1.head()

,country,year,cereal_yield,fdi_perc_gdp,en_per_gdp,en_per_cap,co2_ttl,co2_per_cap,co2_per_gdp,pop_urb_aggl_perc,prot_area_perc,gdp,gni_per_cap,under_5_mort_rate,pop_growth_perc,pop,urb_pop_growth_perc,urb_pop,gdurb_pop
0,AGO,1991,417.4,5.449515,179.271884,565.451027,4367.397,0.409949,129.971142,15.290728,12.399822,12193746625,820.0,239.1,3.034866,10653515.0,6.687032,4099473,4099473
1,ARE,1991,1594.0,0.076475,245.977706,12262.388130,57010.849,29.851550,598.807980,26.377204,0.266886,33919640390,19340.0,20.5,5.442852,1909812.0,5.265704,1507988,1507988
2,ARG,1991,2666.1,1.285579,173.122857,1434.960601,117021.304,3.536073,426.614517,39.119646,4.772468,189719989668,3960.0,25.8,1.372593,33093579.0,1.762636,28903932,28903932
3,AUS,1991,1603.3,1.306912,208.686644,4926.727783,281530.258,16.288490,689.948873,60.356798,7.915273,329965465819,18380.0,8.6,1.274577,17284000.0,1.438378,14784734,14784734
4,AUT,1991,5463.0,0.209142,128.939160,3381.073790,65888.656,8.448456,322.186648,19.746121,20.991143,172166366529,21200.0,8.9,1.134999,7798899.0,1.134999,5131676,5131676

In [21]:
data1=data1.drop('year',axis=1)

In [26]:
data1=data1.drop('country',axis=1)

In [27]:
data1.head()

,cereal_yield,fdi_perc_gdp,en_per_gdp,en_per_cap,co2_ttl,co2_per_cap,co2_per_gdp,pop_urb_aggl_perc,prot_area_perc,gdp,gni_per_cap,under_5_mort_rate,pop_growth_perc,pop,urb_pop_growth_perc,urb_pop,gdurb_pop
0,417.4,5.449515,179.271884,565.451027,4367.397,0.409949,129.971142,15.290728,12.399822,12193746625,820.0,239.1,3.034866,10653515.0,6.687032,4099473,4099473
1,1594.0,0.076475,245.977706,12262.388130,57010.849,29.851550,598.807980,26.377204,0.266886,33919640390,19340.0,20.5,5.442852,1909812.0,5.265704,1507988,1507988
2,2666.1,1.285579,173.122857,1434.960601,117021.304,3.536073,426.614517,39.119646,4.772468,189719989668,3960.0,25.8,1.372593,33093579.0,1.762636,28903932,28903932
3,1603.3,1.306912,208.686644,4926.727783,281530.258,16.288490,689.948873,60.356798,7.915273,329965465819,18380.0,8.6,1.274577,17284000.0,1.438378,14784734,14784734
4,5463.0,0.209142,128.939160,3381.073790,65888.656,8.448456,322.186648,19.746121,20.991143,172166366529,21200.0,8.9,1.134999,7798899.0,1.134999,5131676,5131676

In [29]:
data1['classify'] = np.where((data1['cereal_yield'] > 550) & (data1['fdi_perc_gdp'] > 2.0) & (data1['en_per_gdp'] > 0.25) & (data1['en_per_cap'] > 250), 'red', 'green')

In [30]:
data1.head()

,cereal_yield,fdi_perc_gdp,en_per_gdp,en_per_cap,co2_ttl,co2_per_cap,co2_per_gdp,pop_urb_aggl_perc,prot_area_perc,gdp,gni_per_cap,under_5_mort_rate,pop_growth_perc,pop,urb_pop_growth_perc,urb_pop,gdurb_pop,classify
0,417.4,5.449515,179.271884,565.451027,4367.397,0.409949,129.971142,15.290728,12.399822,12193746625,820.0,239.1,3.034866,10653515.0,6.687032,4099473,4099473,green
1,1594.0,0.076475,245.977706,12262.388130,57010.849,29.851550,598.807980,26.377204,0.266886,33919640390,19340.0,20.5,5.442852,1909812.0,5.265704,1507988,1507988,green
2,2666.1,1.285579,173.122857,1434.960601,117021.304,3.536073,426.614517,39.119646,4.772468,189719989668,3960.0,25.8,1.372593,33093579.0,1.762636,28903932,28903932,green
3,1603.3,1.306912,208.686644,4926.727783,281530.258,16.288490,689.948873,60.356798,7.915273,329965465819,18380.0,8.6,1.274577,17284000.0,1.438378,14784734,14784734,green
4,5463.0,0.209142,128.939160,3381.073790,65888.656,8.448456,322.186648,19.746121,20.991143,172166366529,21200.0,8.9,1.134999,7798899.0,1.134999,5131676,5131676,green

In [38]:
data1['classify'].value_counts()

green    873
red      827
Name: classify, dtype: int64

In [44]:
len(data1.columns)

18

In [39]:
X = data1.iloc[:, :-1].values
y = data1.iloc[:, -1].values

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [41]:
print(X_train)

[[2845.1 2.64321685940547 561.792198542983 ... -0.551496604991644
  '32105753' '32105753']
 [2084.8 0.199382436194323 297.01622640808 ... 2.69718153576026
  '235264466' '235264466']
 [2399.4 0.721105269931709 230.172804218954 ... 2.20074102968657
  '301224807' '301224807']
 ...
 [1416.6 0.318285504555505 321.601101321551 ... 3.95384227140132
  '8306370' '8306370']
 [1953.7 1.74359703070132 202.834036319809 ... 1.37326707429618
  '16024612' '16024612']
 [6661.5 5.12735149911499 136.669234940985 ... 0.381090475331556
  '52193925' '52193925']]

In [45]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [46]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [47]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'red']
 ['red' 'red']
 ['green' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'green']
 ['red' 'red']
 ['green' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'green']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['red' 'red']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['red' 'red']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']
 ['green' 'green']]

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[234   5]
 [ 11 175]]

0.9623529411764706

In [49]:
import joblib

In [51]:
joblib.dump(classifier,"svc.pkl")

['svc.pkl']